// I keep UB's academic structure here so login and dashboard scopes use one source of truth.
export const UB_FACULTY_DEPARTMENTS: Record<string, string[]> = {
  "Faculty of Arts": [
    "Department Of English",
    "Department Of French",
    "Department Of History",
    "Department Of Linguistics",
    "Department Of Performing And Visual Arts",
  ],
  "Faculty of Veterinary Medicine and Agriculture": [
    "Department of Agricultural Economics and Agribusiness",
    "Department of Agricultural Extension and Rural Development",
    "Department of Agronomic and Applied Molecular Sciences",
    "Department of Animal Science",
    "Department of Food Science and Technology",
    "Department of Forestry and Wildlife",
    "Department of Veterinary Medicine",
  ],
  "Faculty of Education": [
    "Department of Curriculum Studies and Teaching (CST)",
    "Department of Educational Foundations Administration (EFA)",
    "Department of Educational Psychology (EPY)",
  ],
  "Faculty of Engineering and Technology": [
    "Department of Computer Engineering",
    "Department of Electrical and Electronic Engineering",
    "Department of Civil Engineering",
  ],
  "Faculty of Health Sciences": [
    "Department of Biomedical Sciences",
    "Department of Nursing",
    "Department of Medical Laboratory Sciences",
    "Department of Public Health and Hygiene",
  ],
  "Faculty of Science": [
    "Department Of Biochemistry and Molecular Biology",
    "Department Of Botany and Plant Physiology",
    "Department Of Chemistry",
    "Department Of Computer Science",
    "Department Of Environmental Science",
    "Department Of Geology",
    "Department Of Mathematics",
    "Department Of Microbiology and Parasitology",
    "Department Of Physics",
    "Department Of Zoology and Animal Physiology",
  ],
  "Faculty of Social and Management Sciences (SMS)": [
    "Department Of Banking and Finance",
    "Department Of Economics and Management",
    "Department Of Management",
    "Department Of Geography",
    "Department Of Journalism and Mass Communications",
    "Department Of Sociology and Anthropology",
    "Department Of Women and Gender Studies",
  ],
  "Faculty of Laws and Political Science": [
    "Department of Business Law",
    "Department of Civil Law",
    "Department of English Law",
    "Department of Political Science and Comparative Politics",
    "Department of Public Law and Public Administration",
    "Department of International Relations and Conflict Resolutions",
  ],
  "College of Technology (COT)": [
    "Department of Computer Engineering",
    "Department of Electrical and Electronic Engineering",
    "Department of Mechanical Engineering",
  ],
  "Higher Technical Teachers' Training College Kumba (HTTTC)": [
    "Department Of Administrative Techniques",
    "Department Of Agriculture",
    "Department Of Civil Engineering and Forestry Techniques",
    "Department Of Computer Science",
    "Department Of Electrical and Power Engineering",
    "Department Of Guidance Counselling",
    "Department Of Law",
    "Department Of Management Science",
    "Department Of Mechanical Engineering",
    "Department Of Renewable Energy",
    "Department Of Science of Education",
    "Department Of Social Economy and Family Management",
    "Department Of Topography and Real Estate Management",
    "Department Of Tourism and Hospitality Management",
  ],
  "Advanced School of Translators and Interpreters (ASTI)": [
    "Department Of General Studies And Promotion Of Bilingualism",
    "Department Of Interpretation",
    "Department Of Translation",
  ],
};

export const UB_FACULTY_OPTIONS = Object.keys(UB_FACULTY_DEPARTMENTS).sort();
